import LegalPageWrapper from '@/components/LegalPageWrapper'

export default function DisclaimerPage() {
  return (
    <LegalPageWrapper title="Website Disclaimer" updated="July 2026">

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">1. General Disclaimer</h2>
        <p className="leading-relaxed">
          The information provided on tagyourproject.com and through the TAGS platform is for general informational and operational purposes only. While TAGS strives to keep information accurate and up to date, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the platform or any information, products, services, or related graphics available through it.
        </p>
        <p className="leading-relaxed mt-3">
          Your use of the TAGS platform is entirely at your own risk. In no event will TAGS be liable for any loss or damage — including, without limitation, indirect or consequential loss or damage — arising from your use of the platform.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">2. AI-Generated Content</h2>
        <p className="leading-relaxed">
          TAGS uses artificial intelligence to generate Scopes of Work. These documents are produced automatically from user-submitted descriptions and photos using Anthropic&apos;s Claude language model. AI-generated content has inherent limitations:
        </p>
        <ul className="space-y-2 list-disc list-inside leading-relaxed mt-3">
          <li>A Scope of Work generated by TAGS is <strong className="text-white">not professional engineering, architectural, or legal advice.</strong></li>
          <li>AI-generated SOWs may omit materials, labor, code requirements, or permit obligations specific to your jurisdiction, property type, or trade.</li>
          <li>The AI model does not physically inspect properties and cannot account for conditions not described or visible in uploaded photos.</li>
          <li>TAGS does not guarantee that any AI-generated SOW is complete, compliant with local building codes, or sufficient for all contractual or insurance purposes.</li>
        </ul>
        <p className="leading-relaxed mt-3">
          Property managers are solely responsible for reviewing AI-generated SOWs before publishing them for bid. If you are uncertain about the adequacy of a scope for a complex or high-stakes project, consult a licensed professional.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">3. Contractor Quality</h2>
        <p className="leading-relaxed">
          TAGS reviews contractor applications and verifies that applicants represent holding current licenses and insurance. However, TAGS is not a contractor licensing board, bonding agency, or insurance underwriter. TAGS:
        </p>
        <ul className="space-y-2 list-disc list-inside leading-relaxed mt-3">
          <li>Does not guarantee the quality, safety, legality, or timely completion of any work performed by a contractor.</li>
          <li>Does not independently verify that contractor licenses and insurance are currently active at the time of each project.</li>
          <li>Is not a party to any contract between a property manager and a contractor.</li>
          <li>Is not responsible for disputes, damages, injuries, or losses arising from contractor work.</li>
        </ul>
        <p className="leading-relaxed mt-3">
          Property managers are encouraged to independently verify contractor credentials before awarding bids, particularly for high-value or safety-sensitive projects.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">4. Platform Availability</h2>
        <p className="leading-relaxed">
          TAGS makes reasonable efforts to keep the platform online and performant. However, we do not guarantee uninterrupted, error-free access to tagyourproject.com. The platform may be temporarily unavailable due to maintenance, technical issues, third-party service disruptions (Supabase, Netlify, Anthropic, Twilio, Stripe), or circumstances beyond our control.
        </p>
        <p className="leading-relaxed mt-3">
          TAGS is not liable for any loss or damage caused by temporary unavailability of the platform, including missed bids, delayed project starts, or communication failures.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">5. Pricing & Fees</h2>
        <p className="leading-relaxed">
          All pricing displayed on tagyourproject.com is subject to change with notice. TAGS is currently in beta, and pricing shown reflects beta rates. TAGS reserves the right to introduce, modify, or discontinue pricing tiers with 30 days written notice to active users. Early access accounts will be grandfathered at their current rates.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">6. Third-Party Links & Services</h2>
        <p className="leading-relaxed">
          The TAGS platform may contain links to or integrations with third-party websites and services. These links are provided for your convenience only. TAGS has no control over the content, privacy practices, or policies of third-party sites and accepts no responsibility for them. Your use of any linked third-party service is governed by that service&apos;s own terms.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">7. No Professional Advice</h2>
        <p className="leading-relaxed">
          Nothing on tagyourproject.com constitutes legal, financial, engineering, architectural, or professional advice. TAGS is a technology marketplace. If you require professional guidance on a construction project, contract dispute, or regulatory compliance matter, consult a qualified professional licensed in your jurisdiction.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">8. Contact</h2>
        <p className="leading-relaxed">
          Questions about this disclaimer? Reach us at <a href="mailto:hello@tagyourproject.com" className="underline" style={{ color: 'oklch(0.57 0.135 183)' }}>hello@tagyourproject.com</a>.
        </p>
      </section>

    </LegalPageWrapper>
  )
}
