import LegalPageWrapper from '@/components/LegalPageWrapper'

export default function IPNoticePage() {
  return (
    <LegalPageWrapper title="Intellectual Property & Copyright" updated="July 2026">

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">1. TAGS Platform Ownership</h2>
        <p className="leading-relaxed">
          The TAGS platform — including its website, mobile interface, software, databases, data models, algorithms, user interface design, source code, and documentation — is the exclusive property of TAGS — The Apartment Guys System (&ldquo;TAGS&rdquo;). All rights reserved.
        </p>
        <p className="leading-relaxed mt-3">
          The TAGS name, logo, tagline, and brand elements are trademarks of TAGS — The Apartment Guys System. You may not use TAGS trademarks, logos, or trade names without prior written permission from TAGS.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">2. AI-Generated Scopes of Work</h2>
        <p className="leading-relaxed">
          All Scopes of Work generated by the TAGS platform are the intellectual property of TAGS — The Apartment Guys System. This includes the structure, format, section headings, and AI-generated content within each SOW document.
        </p>
        <p className="leading-relaxed mt-3">You may use SOWs generated on the TAGS platform for the following purposes:</p>
        <ul className="space-y-2 list-disc list-inside leading-relaxed mt-3">
          <li>Soliciting and evaluating bids from contractors within the TAGS platform.</li>
          <li>Sharing with a contractor you have engaged through TAGS for the purpose of completing the described work.</li>
          <li>Internal recordkeeping and communication within your organization.</li>
        </ul>
        <p className="leading-relaxed mt-3">
          You may not reproduce, republish, resell, sublicense, or distribute AI-generated SOWs outside your organization or for any commercial purpose without TAGS&apos;s prior written permission.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">3. User-Uploaded Content</h2>
        <p className="leading-relaxed">
          You retain ownership of all content you upload to the TAGS platform — including project descriptions, photos, bid documents, and messages (&ldquo;User Content&rdquo;). By uploading User Content, you grant TAGS a non-exclusive, worldwide, royalty-free license to:
        </p>
        <ul className="space-y-2 list-disc list-inside leading-relaxed mt-3">
          <li>Store and display your User Content within the TAGS platform.</li>
          <li>Process your User Content through AI systems (including Anthropic&apos;s Claude API) for the purpose of generating Scopes of Work.</li>
          <li>Use anonymized, aggregated User Content to improve the platform and its AI capabilities.</li>
        </ul>
        <p className="leading-relaxed mt-3">
          TAGS will not display your User Content publicly, sell it, or share it with third parties outside the service providers described in our <a href="/privacy" className="underline" style={{ color: 'oklch(0.57 0.135 183)' }}>Privacy Policy</a>.
        </p>
        <p className="leading-relaxed mt-3">
          You represent and warrant that you have all necessary rights to upload your User Content and that doing so does not infringe any third-party intellectual property rights, privacy rights, or applicable laws.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">4. Third-Party Technology</h2>
        <p className="leading-relaxed">
          TAGS is built on and integrates with third-party technologies whose intellectual property belongs to their respective owners:
        </p>
        <ul className="space-y-2 list-disc list-inside leading-relaxed mt-3">
          <li><strong className="text-white">Anthropic / Claude</strong> — AI language model used for SOW generation. Content generated through Claude is processed under Anthropic&apos;s usage policies.</li>
          <li><strong className="text-white">Supabase</strong> — Database and authentication infrastructure.</li>
          <li><strong className="text-white">Netlify</strong> — Hosting and deployment infrastructure.</li>
          <li><strong className="text-white">Twilio</strong> — SMS notification infrastructure.</li>
          <li><strong className="text-white">Stripe</strong> — Payment processing infrastructure.</li>
          <li><strong className="text-white">Next.js / React / Tailwind CSS</strong> — Open-source frontend framework and UI library.</li>
        </ul>
        <p className="leading-relaxed mt-3">
          TAGS&apos;s use of these technologies does not transfer any ownership of them to users of the TAGS platform.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">5. Copyright Infringement (DMCA)</h2>
        <p className="leading-relaxed">
          If you believe that any content on the TAGS platform infringes your copyright, please send a notice to <a href="mailto:hello@tagyourproject.com" className="underline" style={{ color: 'oklch(0.57 0.135 183)' }}>hello@tagyourproject.com</a> with the following information:
        </p>
        <ul className="space-y-2 list-disc list-inside leading-relaxed mt-3">
          <li>A description of the copyrighted work you claim has been infringed.</li>
          <li>A description of where the alleged infringing material is located on the platform.</li>
          <li>Your contact information (name, address, phone number, and email).</li>
          <li>A statement that you have a good faith belief that the use is not authorized by the copyright owner, its agent, or the law.</li>
          <li>A statement, under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on their behalf.</li>
          <li>Your physical or electronic signature.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">6. License to Use the Platform</h2>
        <p className="leading-relaxed">
          Subject to your compliance with these terms and the TAGS Terms of Service, TAGS grants you a limited, non-exclusive, non-transferable, revocable license to access and use the TAGS platform for its intended purpose — posting and managing repair projects or submitting bids, as applicable to your role.
        </p>
        <p className="leading-relaxed mt-3">
          This license does not permit you to: copy, modify, or create derivative works of the platform; reverse engineer or attempt to extract the platform&apos;s source code; scrape, crawl, or systematically extract data from the platform; or use the platform to build a competing product.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-white mb-3">7. Contact</h2>
        <p className="leading-relaxed">
          IP questions? Reach us at <a href="mailto:hello@tagyourproject.com" className="underline" style={{ color: 'oklch(0.57 0.135 183)' }}>hello@tagyourproject.com</a>.
        </p>
      </section>

    </LegalPageWrapper>
  )
}
